<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Ciudad;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ciudades')->insert([
            ['nombre_ciudad' => 'La Ceiba', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Tela', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Jutiapa', 'departamento_id' => 1],
            ['nombre_ciudad' => 'La Masica', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Arizona', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Esparta', 'departamento_id' => 1],
            ['nombre_ciudad' => 'San Francisco', 'departamento_id' => 1],
            ['nombre_ciudad' => 'San Francisco del Norte', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Punta Sal', 'departamento_id' => 1],
            ['nombre_ciudad' => 'Trujillo', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Tocoa', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Sonaguera', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Bonito Oriental', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Sabá', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Santa Fe', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Santa Rosa de Aguán', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Limón', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Iriona', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Balfate', 'departamento_id' => 2],
            ['nombre_ciudad' => 'Comayagua', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Ajuterique', 'departamento_id' => 3],
            ['nombre_ciudad' => 'El Rosario', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Esquías', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Humuya', 'departamento_id' => 3],
            ['nombre_ciudad' => 'La Libertad', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Lamaní', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Las Lajas', 'departamento_id' => 3],
            ['nombre_ciudad' => 'La Trinidad', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Lejamaní', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Meámbar', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Minas de Oro', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Ojos de Agua', 'departamento_id' => 3],
            ['nombre_ciudad' => 'San Jerónimo', 'departamento_id' => 3],
            ['nombre_ciudad' => 'San José de Comayagua', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Siguatepeque', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Villa de San Antonio', 'departamento_id' => 3],
            ['nombre_ciudad' => 'Santa Rosa de Copán', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Cabañas', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Concepción', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Copán Ruinas', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Corquín', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Cucuyagua', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Dolores', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Dulce Nombre', 'departamento_id' => 4],
            ['nombre_ciudad' => 'El Paraíso', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Florida', 'departamento_id' => 4],
            ['nombre_ciudad' => 'La Jigua', 'departamento_id' => 4],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Nueva Arcadia', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Agustín', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Antonio', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Jerónimo', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San José', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Juan de Opoa', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Nicolás', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Pedro', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Santa Rita', 'departamento_id' => 4],
            ['nombre_ciudad' => 'Trinidad de Copán', 'departamento_id' => 4],
            ['nombre_ciudad' => 'San Pedro Sula', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Choloma', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Omoa', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Puerto Cortés', 'departamento_id' => 5],
            ['nombre_ciudad' => 'La Lima', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Villanueva', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Pimienta', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Potrerillos', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Antonio de Cortés', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Santa Cruz de Yojoa', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Francisco de Yojoa', 'departamento_id' => 5],
            ['nombre_ciudad' => 'San Manuel', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Villanueva', 'departamento_id' => 5],
            ['nombre_ciudad' => 'Yuscarán', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Alauca', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Danlí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'El Paraíso', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Guinope', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Jacaleapa', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Liure', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Morocelí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Oropolí', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Potrerillos', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Antonio de Flores', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Lucas', 'departamento_id' => 6],
            ['nombre_ciudad' => 'San Matías', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Soledad', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Teupasenti', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Texiguat', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Trojes', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Vado Ancho', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Yauyupe', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Alubarén', 'departamento_id' => 6],
            ['nombre_ciudad' => 'Tegucigalpa', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Valle de Ángeles', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Santa Lucía', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Talanga', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Villa de San Francisco', 'departamento_id' => 7],
            ['nombre_ciudad' => 'San Ignacio', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Guaimaca', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Nueva Armenia', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Orica', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Distrito Central', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Ojojona', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Valle de Ángeles', 'departamento_id' => 7],
            ['nombre_ciudad' => 'Puerto Lempira', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Brus Laguna', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Ahuas', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Wampusirpi', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Villeda Morales', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Juan Francisco Bulnes', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Raista', 'departamento_id' => 8],
            ['nombre_ciudad' => 'Paplaya', 'departamento_id' => 8],
            ['nombre_ciudad' => 'La Esperanza', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Intibucá', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Camasca', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Colomoncagua', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Concepción', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Dolores', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Magdalena', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Masaguara', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Antonio', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Isidro', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Juan', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Marcos de la Sierra', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Miguelito', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Santa Lucía', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Yamaranguila', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Isidro', 'departamento_id' => 9],
            ['nombre_ciudad' => 'San Juan de Dios', 'departamento_id' => 9],
            ['nombre_ciudad' => 'Roatán', 'departamento_id' => 10],
            ['nombre_ciudad' => 'José Santos Guardiola', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Guanaja', 'departamento_id' => 10],
            ['nombre_ciudad' => 'Utila', 'departamento_id' => 10],
            ['nombre_ciudad' => 'La Paz', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Aguanqueterique', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Cabañas', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Cane', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Chinacla', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Guajiquiro', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Lauterique', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Marcala', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Mercedes de Oriente', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Opatoro', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Antonio del Norte', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San José', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Juan', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Pedro de Tutule', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Santa Ana', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Santa Elena', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San José', 'departamento_id' => 11],
            ['nombre_ciudad' => 'San Marcos', 'departamento_id' => 11],
            ['nombre_ciudad' => 'Gracias', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Belén', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Candelaria', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Cololaca', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Erandique', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Gualcince', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Guarita', 'departamento_id' => 12],
            ['nombre_ciudad' => 'La Campa', 'departamento_id' => 12],
            ['nombre_ciudad' => 'La Iguala', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Las Flores', 'departamento_id' => 12],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 12],
            ['nombre_ciudad' => 'La Virtud', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Lepaera', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Mapulaca', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Piraera', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San Andrés', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San Francisco', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San Juan Guarita', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San Manuel Colohete', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San Rafael', 'departamento_id' => 12],
            ['nombre_ciudad' => 'San Sebastián', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Santa Cruz', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Talgua', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Tambla', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Tomalá', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Valladolid', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Virginia', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Gracias a Dios', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Guarita', 'departamento_id' => 12],
            ['nombre_ciudad' => 'Nueva Ocotepeque', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Belén Gualcho', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Concepción', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Dolores Merendón', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Fraternidad', 'departamento_id' => 13],
            ['nombre_ciudad' => 'La Encarnación', 'departamento_id' => 13],
            ['nombre_ciudad' => 'La Labor', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Lucerna', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Mercedes', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Fernando', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Francisco del Valle', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Jorge', 'departamento_id' => 13],
            ['nombre_ciudad' => 'San Marcos', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Santa Fe', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Sensenti', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Sinuapa', 'departamento_id' => 13],
            ['nombre_ciudad' => 'Juticalpa', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Campamento', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Catacamas', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Concordia', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Dulce Nombre de Culmí', 'departamento_id' => 14],
            ['nombre_ciudad' => 'El Rosario', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Esquipulas del Norte', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Gualaco', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Guarizama', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Jano', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Unión', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Mangulile', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Manto', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Salamá', 'departamento_id' => 14],
            ['nombre_ciudad' => 'San Esteban', 'departamento_id' => 14],
            ['nombre_ciudad' => 'San Francisco de Becerra', 'departamento_id' => 14],
            ['nombre_ciudad' => 'San Francisco de la Paz', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Santa María del Real', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Silca', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Yocón', 'departamento_id' => 14],
            ['nombre_ciudad' => 'San Francisco de La Paz', 'departamento_id' => 14],
            ['nombre_ciudad' => 'La Libertad', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Santa Cruz de Yojoa', 'departamento_id' => 14],
            ['nombre_ciudad' => 'Santa Bárbara', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Arada', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Atima', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Azacualpa', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Ceguaca', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Concepción del Norte', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Concepción del Sur', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Chinda', 'departamento_id' => 15],
            ['nombre_ciudad' => 'El Níspero', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Gualala', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Ilama', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Las Vegas', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Macuelizo', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Naranjito', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Nuevo Celilac', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Petoa', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Protección', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Quimistán', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Francisco de Ojuera', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San José de Colinas', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Luis', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Marcos', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Nicolás', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Pedro Zacapa', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Santa Rita', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Trinidad', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Las Vegas', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Nuevo Celilac', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Petoa', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Sebastián', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Vicente', 'departamento_id' => 15],
            ['nombre_ciudad' => 'San Fernando', 'departamento_id' => 15],
            ['nombre_ciudad' => 'Nacaome', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Alianza', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Amapala', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Aramecina', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Caridad', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Goascorán', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Langue', 'departamento_id' => 16],
            ['nombre_ciudad' => 'San Francisco de Coray', 'departamento_id' => 16],
            ['nombre_ciudad' => 'San Lorenzo', 'departamento_id' => 16],
            ['nombre_ciudad' => 'San Marcos', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Santa Ana', 'departamento_id' => 16],
            ['nombre_ciudad' => 'San Jerónimo', 'departamento_id' => 16],
            ['nombre_ciudad' => 'San Antonio', 'departamento_id' => 16],
            ['nombre_ciudad' => 'Yoro', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Arenal', 'departamento_id' => 17],
            ['nombre_ciudad' => 'El Negrito', 'departamento_id' => 17],
            ['nombre_ciudad' => 'El Progreso', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Jocón', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Morazán', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Olanchito', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Santa Rita', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Sulaco', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Victoria', 'departamento_id' => 17],
            ['nombre_ciudad' => 'La Concordia', 'departamento_id' => 17],
            ['nombre_ciudad' => 'El Triunfo', 'departamento_id' => 17],
            ['nombre_ciudad' => 'Choluteca', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Apacilagua', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Concepción de María', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Duyure', 'departamento_id' => 18],
            ['nombre_ciudad' => 'El Corpus', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Marcovia', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Morolica', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Namasigüe', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Orocuina', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Pespire', 'departamento_id' => 18],
            ['nombre_ciudad' => 'San Antonio de Flores', 'departamento_id' => 18],
            ['nombre_ciudad' => 'San Isidro', 'departamento_id' => 18],
            ['nombre_ciudad' => 'San José', 'departamento_id' => 18],
            ['nombre_ciudad' => 'San Marcos de Colón', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Santa Ana de Yusguare', 'departamento_id' => 18],
            ['nombre_ciudad' => 'El Triunfo', 'departamento_id' => 18],
            ['nombre_ciudad' => 'La Venta', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Morolica', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Namasigüe', 'departamento_id' => 18],
            ['nombre_ciudad' => 'San Lucas', 'departamento_id' => 18],
            ['nombre_ciudad' => 'Cabañas', 'departamento_id' => 18],
        ]);
    }
}