<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [
            ['nombre_pais' => 'Afganistán', 'codigo_alfa3' => 'AFG', 'codigo_numerico' => '004'],
            ['nombre_pais' => 'Albania', 'codigo_alfa3' => 'ALB', 'codigo_numerico' => '008'],
            ['nombre_pais' => 'Alemania', 'codigo_alfa3' => 'DEU', 'codigo_numerico' => '276'],
            ['nombre_pais' => 'Andorra', 'codigo_alfa3' => 'AND', 'codigo_numerico' => '020'],
            ['nombre_pais' => 'Angola', 'codigo_alfa3' => 'AGO', 'codigo_numerico' => '024'],
            ['nombre_pais' => 'Antigua y Barbuda', 'codigo_alfa3' => 'ATG', 'codigo_numerico' => '028'],
            ['nombre_pais' => 'Arabia Saudita', 'codigo_alfa3' => 'SAU', 'codigo_numerico' => '682'],
            ['nombre_pais' => 'Argelia', 'codigo_alfa3' => 'DZA', 'codigo_numerico' => '012'],
            ['nombre_pais' => 'Argentina', 'codigo_alfa3' => 'ARG', 'codigo_numerico' => '032'],
            ['nombre_pais' => 'Armenia', 'codigo_alfa3' => 'ARM', 'codigo_numerico' => '051'],
            ['nombre_pais' => 'Australia', 'codigo_alfa3' => 'AUS', 'codigo_numerico' => '036'],
            ['nombre_pais' => 'Austria', 'codigo_alfa3' => 'AUT', 'codigo_numerico' => '040'],
            ['nombre_pais' => 'Azerbaiyán', 'codigo_alfa3' => 'AZE', 'codigo_numerico' => '031'],
            ['nombre_pais' => 'Bahamas', 'codigo_alfa3' => 'BHS', 'codigo_numerico' => '044'],
            ['nombre_pais' => 'Bangladesh', 'codigo_alfa3' => 'BGD', 'codigo_numerico' => '050'],
            ['nombre_pais' => 'Barbados', 'codigo_alfa3' => 'BRB', 'codigo_numerico' => '052'],
            ['nombre_pais' => 'Baréin', 'codigo_alfa3' => 'BHR', 'codigo_numerico' => '048'],
            ['nombre_pais' => 'Bélgica', 'codigo_alfa3' => 'BEL', 'codigo_numerico' => '056'],
            ['nombre_pais' => 'Belice', 'codigo_alfa3' => 'BLZ', 'codigo_numerico' => '084'],
            ['nombre_pais' => 'Benín', 'codigo_alfa3' => 'BEN', 'codigo_numerico' => '204'],
            ['nombre_pais' => 'Bielorrusia', 'codigo_alfa3' => 'BLR', 'codigo_numerico' => '112'],
            ['nombre_pais' => 'Birmania', 'codigo_alfa3' => 'MMR', 'codigo_numerico' => '104'],
            ['nombre_pais' => 'Bolivia', 'codigo_alfa3' => 'BOL', 'codigo_numerico' => '068'],
            ['nombre_pais' => 'Bosnia y Herzegovina', 'codigo_alfa3' => 'BIH', 'codigo_numerico' => '070'],
            ['nombre_pais' => 'Botsuana', 'codigo_alfa3' => 'BWA', 'codigo_numerico' => '072'],
            ['nombre_pais' => 'Brasil', 'codigo_alfa3' => 'BRA', 'codigo_numerico' => '076'],
            ['nombre_pais' => 'Brunéi', 'codigo_alfa3' => 'BRN', 'codigo_numerico' => '096'],
            ['nombre_pais' => 'Bulgaria', 'codigo_alfa3' => 'BGR', 'codigo_numerico' => '100'],
            ['nombre_pais' => 'Burkina Faso', 'codigo_alfa3' => 'BFA', 'codigo_numerico' => '854'],
            ['nombre_pais' => 'Burundi', 'codigo_alfa3' => 'BDI', 'codigo_numerico' => '108'],
            ['nombre_pais' => 'Cabo Verde', 'codigo_alfa3' => 'CPV', 'codigo_numerico' => '132'],
            ['nombre_pais' => 'Camboya', 'codigo_alfa3' => 'KHM', 'codigo_numerico' => '116'],
            ['nombre_pais' => 'Camerún', 'codigo_alfa3' => 'CMR', 'codigo_numerico' => '120'],
            ['nombre_pais' => 'Canadá', 'codigo_alfa3' => 'CAN', 'codigo_numerico' => '124'],
            ['nombre_pais' => 'Chad', 'codigo_alfa3' => 'TCD', 'codigo_numerico' => '148'],
            ['nombre_pais' => 'Chile', 'codigo_alfa3' => 'CHL', 'codigo_numerico' => '152'],
            ['nombre_pais' => 'China', 'codigo_alfa3' => 'CHN', 'codigo_numerico' => '156'],
            ['nombre_pais' => 'Chipre', 'codigo_alfa3' => 'CYP', 'codigo_numerico' => '196'],
            ['nombre_pais' => 'Colombia', 'codigo_alfa3' => 'COL', 'codigo_numerico' => '170'],
            ['nombre_pais' => 'Comoras', 'codigo_alfa3' => 'COM', 'codigo_numerico' => '174'],
            ['nombre_pais' => 'Congo', 'codigo_alfa3' => 'COG', 'codigo_numerico' => '178'],
            ['nombre_pais' => 'Corea del Norte', 'codigo_alfa3' => 'PRK', 'codigo_numerico' => '408'],
            ['nombre_pais' => 'Corea del Sur', 'codigo_alfa3' => 'KOR', 'codigo_numerico' => '410'],
            ['nombre_pais' => 'Costa de Marfil', 'codigo_alfa3' => 'CIV', 'codigo_numerico' => '384'],
            ['nombre_pais' => 'Costa Rica', 'codigo_alfa3' => 'CRI', 'codigo_numerico' => '188'],
            ['nombre_pais' => 'Croacia', 'codigo_alfa3' => 'HRV', 'codigo_numerico' => '191'],
            ['nombre_pais' => 'Cuba', 'codigo_alfa3' => 'CUB', 'codigo_numerico' => '192'],
            ['nombre_pais' => 'Dinamarca', 'codigo_alfa3' => 'DNK', 'codigo_numerico' => '208'],
            ['nombre_pais' => 'Ecuador', 'codigo_alfa3' => 'ECU', 'codigo_numerico' => '218'],
            ['nombre_pais' => 'Egipto', 'codigo_alfa3' => 'EGY', 'codigo_numerico' => '818'],
            ['nombre_pais' => 'El Salvador', 'codigo_alfa3' => 'SLV', 'codigo_numerico' => '222'],
            ['nombre_pais' => 'Emiratos Árabes Unidos', 'codigo_alfa3' => 'ARE', 'codigo_numerico' => '784'],
            ['nombre_pais' => 'Eritrea', 'codigo_alfa3' => 'ERI', 'codigo_numerico' => '232'],
            ['nombre_pais' => 'Eslovaquia', 'codigo_alfa3' => 'SVK', 'codigo_numerico' => '703'],
            ['nombre_pais' => 'Eslovenia', 'codigo_alfa3' => 'SVN', 'codigo_numerico' => '705'],
            ['nombre_pais' => 'España', 'codigo_alfa3' => 'ESP', 'codigo_numerico' => '724'],
            ['nombre_pais' => 'Estados Unidos', 'codigo_alfa3' => 'USA', 'codigo_numerico' => '840'],
            ['nombre_pais' => 'Estonia', 'codigo_alfa3' => 'EST', 'codigo_numerico' => '233'],
            ['nombre_pais' => 'Esuatini', 'codigo_alfa3' => 'SWZ', 'codigo_numerico' => '748'],
            ['nombre_pais' => 'Etiopía', 'codigo_alfa3' => 'ETH', 'codigo_numerico' => '231'],
            ['nombre_pais' => 'Filipinas', 'codigo_alfa3' => 'PHL', 'codigo_numerico' => '608'],
            ['nombre_pais' => 'Finlandia', 'codigo_alfa3' => 'FIN', 'codigo_numerico' => '246'],
            ['nombre_pais' => 'Francia', 'codigo_alfa3' => 'FRA', 'codigo_numerico' => '250'],
            ['nombre_pais' => 'Gabón', 'codigo_alfa3' => 'GAB', 'codigo_numerico' => '266'],
            ['nombre_pais' => 'Gambia', 'codigo_alfa3' => 'GMB', 'codigo_numerico' => '270'],
            ['nombre_pais' => 'Georgia', 'codigo_alfa3' => 'GEO', 'codigo_numerico' => '268'],
            ['nombre_pais' => 'Ghana', 'codigo_alfa3' => 'GHA', 'codigo_numerico' => '288'],
            ['nombre_pais' => 'Granada', 'codigo_alfa3' => 'GRD', 'codigo_numerico' => '308'],
            ['nombre_pais' => 'Grecia', 'codigo_alfa3' => 'GRC', 'codigo_numerico' => '300'],
            ['nombre_pais' => 'Guinea', 'codigo_alfa3' => 'GIN', 'codigo_numerico' => '324'],
            ['nombre_pais' => 'Guinea-Bisáu', 'codigo_alfa3' => 'GNB', 'codigo_numerico' => '624'],
            ['nombre_pais' => 'Guyana', 'codigo_alfa3' => 'GUY', 'codigo_numerico' => '328'],
            ['nombre_pais' => 'Haití', 'codigo_alfa3' => 'HTI', 'codigo_numerico' => '332'],
            ['nombre_pais' => 'Honduras', 'codigo_alfa3' => 'HND', 'codigo_numerico' => '340'], // Aquí está Honduras
            ['nombre_pais' => 'Hungría', 'codigo_alfa3' => 'HUN', 'codigo_numerico' => '348'],
            ['nombre_pais' => 'Islandia', 'codigo_alfa3' => 'ISL', 'codigo_numerico' => '352'],
            ['nombre_pais' => 'India', 'codigo_alfa3' => 'IND', 'codigo_numerico' => '356'],
            ['nombre_pais' => 'Indonesia', 'codigo_alfa3' => 'IDN', 'codigo_numerico' => '360'],
            ['nombre_pais' => 'Irak', 'codigo_alfa3' => 'IRQ', 'codigo_numerico' => '368'],
            ['nombre_pais' => 'Irán', 'codigo_alfa3' => 'IRN', 'codigo_numerico' => '364'],
            ['nombre_pais' => 'Irlanda', 'codigo_alfa3' => 'IRL', 'codigo_numerico' => '372'],
            ['nombre_pais' => 'Israel', 'codigo_alfa3' => 'ISR', 'codigo_numerico' => '376'],
            ['nombre_pais' => 'Italia', 'codigo_alfa3' => 'ITA', 'codigo_numerico' => '380'],
            ['nombre_pais' => 'Jamaica', 'codigo_alfa3' => 'JAM', 'codigo_numerico' => '388'],
            ['nombre_pais' => 'Japón', 'codigo_alfa3' => 'JPN', 'codigo_numerico' => '392'],
            ['nombre_pais' => 'Jordania', 'codigo_alfa3' => 'JOR', 'codigo_numerico' => '400'],
            ['nombre_pais' => 'Kazajistán', 'codigo_alfa3' => 'KAZ', 'codigo_numerico' => '398'],
            ['nombre_pais' => 'Kenia', 'codigo_alfa3' => 'KEN', 'codigo_numerico' => '404'],
            ['nombre_pais' => 'Kirguistán', 'codigo_alfa3' => 'KGZ', 'codigo_numerico' => '417'],
            ['nombre_pais' => 'Kiribati', 'codigo_alfa3' => 'KIR', 'codigo_numerico' => '296'],
            ['nombre_pais' => 'Kosovo', 'codigo_alfa3' => 'XKX', 'codigo_numerico' => '926'],
            ['nombre_pais' => 'Kuwait', 'codigo_alfa3' => 'KWT', 'codigo_numerico' => '414'],
            ['nombre_pais' => 'Laos', 'codigo_alfa3' => 'LAO', 'codigo_numerico' => '418'],
            ['nombre_pais' => 'Letonia', 'codigo_alfa3' => 'LVA', 'codigo_numerico' => '428'],
            ['nombre_pais' => 'Líbano', 'codigo_alfa3' => 'LBN', 'codigo_numerico' => '422'],
            ['nombre_pais' => 'Lesoto', 'codigo_alfa3' => 'LSO', 'codigo_numerico' => '426'],
            ['nombre_pais' => 'Liberia', 'codigo_alfa3' => 'LBR', 'codigo_numerico' => '430'],
            ['nombre_pais' => 'Libia', 'codigo_alfa3' => 'LBY', 'codigo_numerico' => '434'],
            ['nombre_pais' => 'Liechtenstein', 'codigo_alfa3' => 'LIE', 'codigo_numerico' => '438'],
            ['nombre_pais' => 'Lituania', 'codigo_alfa3' => 'LTU', 'codigo_numerico' => '440'],
            ['nombre_pais' => 'Luxemburgo', 'codigo_alfa3' => 'LUX', 'codigo_numerico' => '442'],
            ['nombre_pais' => 'Madagascar', 'codigo_alfa3' => 'MDG', 'codigo_numerico' => '450'],
            ['nombre_pais' => 'Malaui', 'codigo_alfa3' => 'MWI', 'codigo_numerico' => '454'],
            ['nombre_pais' => 'Malasia', 'codigo_alfa3' => 'MYS', 'codigo_numerico' => '458'],
            ['nombre_pais' => 'Maldivas', 'codigo_alfa3' => 'MDV', 'codigo_numerico' => '462'],
            ['nombre_pais' => 'Malí', 'codigo_alfa3' => 'MLI', 'codigo_numerico' => '466'],
            ['nombre_pais' => 'Malta', 'codigo_alfa3' => 'MLT', 'codigo_numerico' => '470'],
            ['nombre_pais' => 'Marruecos', 'codigo_alfa3' => 'MAR', 'codigo_numerico' => '504'],
            ['nombre_pais' => 'Mauricio', 'codigo_alfa3' => 'MUS', 'codigo_numerico' => '480'],
            ['nombre_pais' => 'Mauritania', 'codigo_alfa3' => 'MRT', 'codigo_numerico' => '478'],
            ['nombre_pais' => 'Micronesia', 'codigo_alfa3' => 'FSM', 'codigo_numerico' => '583'],
            ['nombre_pais' => 'Moldavia', 'codigo_alfa3' => 'MDA', 'codigo_numerico' => '498'],
            ['nombre_pais' => 'Mónaco', 'codigo_alfa3' => 'MCO', 'codigo_numerico' => '492'],
            ['nombre_pais' => 'Mongolia', 'codigo_alfa3' => 'MNG', 'codigo_numerico' => '496'],
            ['nombre_pais' => 'Montenegro', 'codigo_alfa3' => 'MNE', 'codigo_numerico' => '499'],
            ['nombre_pais' => 'Mozambique', 'codigo_alfa3' => 'MOZ', 'codigo_numerico' => '508'],
            ['nombre_pais' => 'Namibia', 'codigo_alfa3' => 'NAM', 'codigo_numerico' => '516'],
            ['nombre_pais' => 'Nauru', 'codigo_alfa3' => 'NRU', 'codigo_numerico' => '520'],
            ['nombre_pais' => 'Nepal', 'codigo_alfa3' => 'NPL', 'codigo_numerico' => '524'],
            ['nombre_pais' => 'Nicaragua', 'codigo_alfa3' => 'NIC', 'codigo_numerico' => '558'],
            ['nombre_pais' => 'Níger', 'codigo_alfa3' => 'NER', 'codigo_numerico' => '562'],
            ['nombre_pais' => 'Nigeria', 'codigo_alfa3' => 'NGA', 'codigo_numerico' => '566'],
            ['nombre_pais' => 'Noruega', 'codigo_alfa3' => 'NOR', 'codigo_numerico' => '578'],
            ['nombre_pais' => 'Nueva Zelanda', 'codigo_alfa3' => 'NZL', 'codigo_numerico' => '554'],
            ['nombre_pais' => 'Omán', 'codigo_alfa3' => 'OMN', 'codigo_numerico' => '512'],
            ['nombre_pais' => 'Países Bajos', 'codigo_alfa3' => 'NLD', 'codigo_numerico' => '528'],
            ['nombre_pais' => 'Pakistán', 'codigo_alfa3' => 'PAK', 'codigo_numerico' => '586'],
            ['nombre_pais' => 'Palaos', 'codigo_alfa3' => 'PLW', 'codigo_numerico' => '585'],
            ['nombre_pais' => 'Panamá', 'codigo_alfa3' => 'PAN', 'codigo_numerico' => '591'],
            ['nombre_pais' => 'Papúa Nueva Guinea', 'codigo_alfa3' => 'PNG', 'codigo_numerico' => '598'],
            ['nombre_pais' => 'Paraguay', 'codigo_alfa3' => 'PRY', 'codigo_numerico' => '600'],
            ['nombre_pais' => 'Perú', 'codigo_alfa3' => 'PER', 'codigo_numerico' => '604'],
            ['nombre_pais' => 'Polonia', 'codigo_alfa3' => 'POL', 'codigo_numerico' => '616'],
            ['nombre_pais' => 'Portugal', 'codigo_alfa3' => 'PRT', 'codigo_numerico' => '620'],
            ['nombre_pais' => 'Reino Unido', 'codigo_alfa3' => 'GBR', 'codigo_numerico' => '826'],
            ['nombre_pais' => 'República Centroafricana', 'codigo_alfa3' => 'CAF', 'codigo_numerico' => '140'],
            ['nombre_pais' => 'República Checa', 'codigo_alfa3' => 'CZE', 'codigo_numerico' => '203'],
            ['nombre_pais' => 'República Dominicana', 'codigo_alfa3' => 'DOM', 'codigo_numerico' => '214'],
            ['nombre_pais' => 'República del Congo', 'codigo_alfa3' => 'COG', 'codigo_numerico' => '178'],
            ['nombre_pais' => 'Rumanía', 'codigo_alfa3' => 'ROU', 'codigo_numerico' => '642'],
            ['nombre_pais' => 'Rusia', 'codigo_alfa3' => 'RUS', 'codigo_numerico' => '643'],
            ['nombre_pais' => 'Ruanda', 'codigo_alfa3' => 'RWA', 'codigo_numerico' => '646'],
            ['nombre_pais' => 'Samoa', 'codigo_alfa3' => 'WSM', 'codigo_numerico' => '882'],
            ['nombre_pais' => 'San Cristóbal y Nieves', 'codigo_alfa3' => 'KNA', 'codigo_numerico' => '659'],
            ['nombre_pais' => 'San Marino', 'codigo_alfa3' => 'SMR', 'codigo_numerico' => '674'],
            ['nombre_pais' => 'San Vicente y las Granadinas', 'codigo_alfa3' => 'VCT', 'codigo_numerico' => '670'],
            ['nombre_pais' => 'Santa Lucía', 'codigo_alfa3' => 'LCA', 'codigo_numerico' => '662'],
            ['nombre_pais' => 'Santo Tomé y Príncipe', 'codigo_alfa3' => 'STP', 'codigo_numerico' => '678'],
            ['nombre_pais' => 'Senegal', 'codigo_alfa3' => 'SEN', 'codigo_numerico' => '686'],
            ['nombre_pais' => 'Serbia', 'codigo_alfa3' => 'SRB', 'codigo_numerico' => '688'],
            ['nombre_pais' => 'Seychelles', 'codigo_alfa3' => 'SYC', 'codigo_numerico' => '690'],
            ['nombre_pais' => 'Sierra Leona', 'codigo_alfa3' => 'SLE', 'codigo_numerico' => '694'],
            ['nombre_pais' => 'Singapur', 'codigo_alfa3' => 'SGP', 'codigo_numerico' => '702'],
            ['nombre_pais' => 'Siria', 'codigo_alfa3' => 'SYR', 'codigo_numerico' => '760'],
            ['nombre_pais' => 'Somalia', 'codigo_alfa3' => 'SOM', 'codigo_numerico' => '706'],
            ['nombre_pais' => 'Sri Lanka', 'codigo_alfa3' => 'LKA', 'codigo_numerico' => '144'],
            ['nombre_pais' => 'Sudáfrica', 'codigo_alfa3' => 'ZAF', 'codigo_numerico' => '710'],
            ['nombre_pais' => 'Sudán', 'codigo_alfa3' => 'SDN', 'codigo_numerico' => '729'],
            ['nombre_pais' => 'Sudán del Sur', 'codigo_alfa3' => 'SSD', 'codigo_numerico' => '728'],
            ['nombre_pais' => 'Suecia', 'codigo_alfa3' => 'SWE', 'codigo_numerico' => '752'],
            ['nombre_pais' => 'Suiza', 'codigo_alfa3' => 'CHE', 'codigo_numerico' => '756'],
            ['nombre_pais' => 'Surinam', 'codigo_alfa3' => 'SUR', 'codigo_numerico' => '740'],
            ['nombre_pais' => 'Tailandia', 'codigo_alfa3' => 'THA', 'codigo_numerico' => '764'],
            ['nombre_pais' => 'Tanzania', 'codigo_alfa3' => 'TZA', 'codigo_numerico' => '834'],
            ['nombre_pais' => 'Tayikistán', 'codigo_alfa3' => 'TJK', 'codigo_numerico' => '762'],
            ['nombre_pais' => 'Timor Oriental', 'codigo_alfa3' => 'TLS', 'codigo_numerico' => '626'],
            ['nombre_pais' => 'Togo', 'codigo_alfa3' => 'TGO', 'codigo_numerico' => '768'],
            ['nombre_pais' => 'Tonga', 'codigo_alfa3' => 'TON', 'codigo_numerico' => '776'],
            ['nombre_pais' => 'Trinidad y Tobago', 'codigo_alfa3' => 'TTO', 'codigo_numerico' => '780'],
            ['nombre_pais' => 'Túnez', 'codigo_alfa3' => 'TUN', 'codigo_numerico' => '788'],
            ['nombre_pais' => 'Turkmenistán', 'codigo_alfa3' => 'TKM', 'codigo_numerico' => '795'],
            ['nombre_pais' => 'Turquía', 'codigo_alfa3' => 'TUR', 'codigo_numerico' => '792'],
            ['nombre_pais' => 'Tuvalu', 'codigo_alfa3' => 'TUV', 'codigo_numerico' => '798'],
            ['nombre_pais' => 'Ucrania', 'codigo_alfa3' => 'UKR', 'codigo_numerico' => '804'],
            ['nombre_pais' => 'Uganda', 'codigo_alfa3' => 'UGA', 'codigo_numerico' => '800'],
            ['nombre_pais' => 'Uruguay', 'codigo_alfa3' => 'URY', 'codigo_numerico' => '858'],
            ['nombre_pais' => 'Uzbekistán', 'codigo_alfa3' => 'UZB', 'codigo_numerico' => '860'],
            ['nombre_pais' => 'Vanuatu', 'codigo_alfa3' => 'VUT', 'codigo_numerico' => '548'],
            ['nombre_pais' => 'Venezuela', 'codigo_alfa3' => 'VEN', 'codigo_numerico' => '862'],
            ['nombre_pais' => 'Vietnam', 'codigo_alfa3' => 'VNM', 'codigo_numerico' => '704'],
            ['nombre_pais' => 'Yemen', 'codigo_alfa3' => 'YEM', 'codigo_numerico' => '887'],
            ['nombre_pais' => 'Yibuti', 'codigo_alfa3' => 'DJI', 'codigo_numerico' => '262'],
            ['nombre_pais' => 'Zambia', 'codigo_alfa3' => 'ZMB', 'codigo_numerico' => '894'],
            ['nombre_pais' => 'Zimbabue', 'codigo_alfa3' => 'ZWE', 'codigo_numerico' => '716'],
        ];

        foreach ($paises as $pais) {
            DB::table('paises')->insert(array_merge($pais, [
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }
    }
}
